# Generated by Django 3.0.7 on 2020-06-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_platform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eval_File_Predict',
            new_name='EvalPredFile',
        ),
        migrations.RenameField(
            model_name='evalpredfile',
            old_name='predict_file',
            new_name='prediction_file',
        ),
    ]
