# Generated by Django 3.0.7 on 2020-08-05 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_platform', '0004_evalpretrainfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalpretrainfile',
            name='description',
            field=models.TextField(default='getting-started'),
        ),
        migrations.AlterField(
            model_name='evalpretrainfile',
            name='epochs',
            field=models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='evalpretrainfile',
            name='max_length',
            field=models.IntegerField(default=120, validators=[django.core.validators.MaxValueValidator(512), django.core.validators.MinValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='evalpretrainfile',
            name='n_classes',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
