# Generated by Django 3.0.7 on 2020-08-17 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_platform', '0005_auto_20200805_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalpretrainfile',
            name='embedding_size',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='evalpretrainfile',
            name='max_features',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='evalpretrainfile',
            name='architecture',
            field=models.CharField(choices=[('cnn_char', 'cnn_char'), ('embed_bilstm_attend', 'embed_bilstm_attend'), ('transformer', 'transformer')], default='cnn_char', max_length=50),
        ),
        migrations.AlterField(
            model_name='evalpretrainfile',
            name='max_length',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(512), django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='evalpretrainfile',
            name='pretrained_model',
            field=models.CharField(choices=[('bert-base-uncased', 'bert-base-uncased'), ('bert-base-cased', 'bert-base-cased'), ('bert-multilingual-cased', 'bert-multilingual-cased'), ('bert-base-german-cased', 'bert-base-german-cased'), ('', '')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='evalpretrainfile',
            name='tokenization',
            field=models.CharField(choices=[('word', 'word'), ('char', 'char'), ('transformer', 'transformer')], default='char', max_length=20),
        ),
    ]
