# Generated by Django 3.0.7 on 2020-08-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_platform', '0006_auto_20200817_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evalpretrainfile',
            name='pretrained_model',
        ),
    ]
